import type { Metadata } from "next";
import localFont from "next/font/local";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import "./globals.css";

const gabriela = localFont({
  src: './fonts/gabriela-regular-webfont.woff',
  variable: '--font-gabriela',
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gabriela.variable}`}>
      <meta name="theme-color" content="#FFFFFF" />
      <body
        className={`max-w-[1440px] mx-auto`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
